# Generated by Django 4.0.4 on 2022-10-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrigerator_item',
            name='insert_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
